//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAHAC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAHAC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;type&quot;:0,&quot;meta&quot;:0,&quot;name&quot;:&quot;Air&quot;,&quot;text_type&quot;:&quot;air&quot;},{&quot;type&quot;:1,&quot;meta&quot;:0,&quot;name&quot;:&quot;Stone&quot;,&quot;text_type&quot;:&quot;stone&quot;},{&quot;type&quot;:1,&quot;meta&quot;:1,&quot;name&quot;:&quot;Granite&quot;,&quot;text_type&quot;:&quot;stone&quot;},{&quot;type&quot;:1,&quot;meta&quot;:2,&quot;name&quot;:&quot;Polished Granite&quot;,&quot;text_type&quot;:&quot;stone&quot;},{&quot;type&quot;:1,&quot;meta&quot;:3,&quot;name&quot;:&quot;Diorite&quot;,&quot;text_type&quot;:&quot;stone&quot;},{&quot;type&quot;:1,&quot;meta&quot;:4,&quot;name&quot;:&quot;Polished Diorite&quot;,&quot;text_type&quot;:&quot;stone&quot;},{&quot;type&quot;:1,&quot;meta&quot;:5,&quot;name&quot;:&quot;Andesite&quot;,&quot;text_type&quot;:&quot;stone&quot;},{&quot;type&quot;:1,&quot;meta&quot;:6,&quot;name&quot;:&quot;Polished Andesite&quot;,&quot;text_type&quot;:&quot;stone&quot;},{&quot;type&quot;:2,&quot;meta&quot;:0,&quot;name&quot;:&quot;G....
        /// </summary>
        internal static string DetailedVanillaItemsInfo {
            get {
                return ResourceManager.GetString("DetailedVanillaItemsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enchanted_item_glint {
            get {
                object obj = ResourceManager.GetObject("enchanted_item_glint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FurfSkyRebornFULL {
            get {
                object obj = ResourceManager.GetObject("FurfSkyRebornFULL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream notify_sound {
            get {
                return ResourceManager.GetStream("notify_sound", resourceCulture);
            }
        }
    }
}
